### ISSUE TITLE
The Device Properties Item in the Context Menu Does not Appear for Unmounted Drives

### ISSUE THREAD

**Issue by MatejGolian** [dvdforge/imgdrive_translations#23]
Currently, if no image is mounted on to a drive, the Device Properties menu item does not appear in the drive's context menu. This is true for the tray menu and the context menus that can be opened from within the main program window as well. Please, consider making the Drive Properties item always available - regardless of whether the drive in question is mounted or not.
Many thanks. :-)

**Comment by oldman777** [comment]
Totally agree, although not previously noticed. 
And since now it's ImgDrive properties, not System properties, I suggest adding any color icon for the difference. 
Thank you. 

![2018-07-11_231301_cr](https://user-images.githubusercontent.com/28647829/42597181-9e4ad7ba-8560-11e8-95fb-803e5e87dcf8.jpg)

**Comment by imgdrive** [comment]
please try v1.4.6: http://download.yubsoft.com/ImgDrive_1.4.6.exe

**Comment by oldman777** [comment]
Yes, fixed and looks great. Thank you!

**Comment by MatejGolian** [comment]
I confirm, it's perfect. :-)
